name: DartPiano
author: Alex Gann
description: Configurable virual piano for Dart
homepage: http://www.dartvn.org/
dependencies:
  browser: any
  stagexl:
    git: git://github.com/realbluesky/StageXL.git
